// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package ir.university.toosi.tms.readerwrapper;

@net.sf.jni4net.attributes.ClrType
public class AccessEventData extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected AccessEventData(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public AccessEventData() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        readerwrapper.AccessEventData.__ctorAccessEventData0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorAccessEventData0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getUserID();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setUserID(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/DateTime;")
    public native system.DateTime getDateTime();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/DateTime;)V")
    public native void setDateTime(system.DateTime value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LReaderWrapper/VirdiAuthMode;")
    public native readerwrapper.VirdiAuthMode getVirdiAuthMode();
    
    @net.sf.jni4net.attributes.ClrMethod("(LReaderWrapper/VirdiAuthMode;)V")
    public native void setVirdiAuthMode(readerwrapper.VirdiAuthMode value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LReaderWrapper/EntryType;")
    public native readerwrapper.EntryType getAuthType();
    
    @net.sf.jni4net.attributes.ClrMethod("(LReaderWrapper/EntryType;)V")
    public native void setAuthType(readerwrapper.EntryType value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isAuthorized();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setIsAuthorized(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native String getRFID();

    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setRFID(String value);

    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getPictureDataLength();

    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setPictureDataLength(int value);

    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Object;")
    public native system.Object getPictureData();

    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;)V")
    public native void setPictureData(system.Object value);

    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getTotalNumber();

    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setTotalNumber(int value);

    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getCurrentIndex();

    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setCurrentIndex(int value);

    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getErrorCode();

    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setErrorCode(int value);

    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native String getFingerImageFormat();

    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setFingerImageFormat(String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getFingerImageLength();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setFingerImageLength(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Object;")
    public native system.Object getFingerImageData();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;)V")
    public native void setFingerImageData(system.Object value);
    
    public static system.Type typeof() {
        return readerwrapper.AccessEventData.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        readerwrapper.AccessEventData.staticType = staticType;
    }
    //</generated-proxy>
}
